name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
  
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://jchhabria:$HF@huggingface.co/spaces/jchhabria/Demo
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://jchhabria:$HF@huggingface.co/spaces/jchhabria/Demo main
