name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
  
jobs:
  sync-to-hub:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add remote
      env:
        HF: ${{ secrets.HF }}
      run: git remote add space https://huggingface.co/spaces/jchhabria/Demo
    - name: Push to hub
      env:
        HF: ${{ secrets.HF }}
      run: git push --force https://huggingface.co/spaces/jchhabria/Demo main
    
```
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a on-line script
      run: echo Hello, world!
      
    - name: Run multi-line script
      run: |
        echo Add pther action to build,
        echo test, and deploy your projct.
 ```  
